---
# See README.md for the rationale behind each of these.
nfs_mounts_shares: []
volume_mount_path: /mnt
nfs_mounts_version: 3
nfs_mounts_rsize: 65536
nfs_mounts_wsize: 65536
nfs_mounts_timeo: 100
nfs_mounts_retrans: 3
