---
- name: Include Docker setup tasks
  ansible.builtin.include_tasks: setup.yml
  when: docker.enabled | default(false)

- name: Include Docker teardown tasks
  ansible.builtin.include_tasks: teardown.yml
  when: not (docker.enabled | default(false))
